@startuml
right header
<font size=24 color=black>Package: <b> ERM_0.0

end header

title
<font size=18 color=black> Електронний реєстр документів
<font size=16 color=black> ER-модель

end title

entity User {
  name
  id
}

entity Archive {
  name
  description
  id
}

entity Record {
  header
  description
}

entity Tag {
  value
}

entity Role {
  name
  description
}

entity Access
entity Link


Access "0.*" ---- "1.1" User
Access "0.*" ---- "1.1" Role
Access "0.*" -u--- "1.1" Archive

Link "0.*" -- "1.1" Record
Link "0.*" -l-- "1.1" Tag

Archive "1.1" -l-- "0.*" Record

right footer

НТУУ КПІ ім.І.Сікорського
Київ-2020
end footer
@enduml
